# Generated by Django 3.1.1 on 2020-10-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='games',
            new_name='game_name',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='athlete_id',
            field=models.IntegerField(unique=True, verbose_name='Id do atleta'),
        ),
    ]
