# Generated by Django 3.1.1 on 2020-10-30 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0002_auto_20201030_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medal',
            name='sport',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athlete.sport')),
            ],
        ),
        migrations.AlterField(
            model_name='medal',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athlete.event'),
        ),
    ]
