# Generated by Django 3.1.1 on 2020-10-31 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0003_auto_20201030_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'ordering': ['athlete_id']},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['game_name']},
        ),
        migrations.AlterModelOptions(
            name='medal',
            options={'ordering': ['athlete__athlete_id']},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['sport']},
        ),
        migrations.AddField(
            model_name='medal',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='athlete.game'),
            preserve_default=False,
        ),
    ]
