# Generated by Django 3.1.1 on 2020-11-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0004_auto_20201031_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event']},
        ),
        migrations.AlterField(
            model_name='sport',
            name='sport',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
