# Generated by Django 3.1.1 on 2020-10-30 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.IntegerField(verbose_name='Id do atleta')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('sex', models.CharField(max_length=1, verbose_name='Sexo')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('height', models.IntegerField(verbose_name='Altura')),
                ('weight', models.IntegerField(verbose_name='Peso')),
                ('team', models.CharField(max_length=100, verbose_name='Equipe/País')),
                ('noc', models.CharField(max_length=3, verbose_name='Siglas')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('medal', models.CharField(max_length=10)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athlete.athlete')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athlete.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.CharField(max_length=200)),
                ('year', models.IntegerField(verbose_name='Ano do Jogo')),
                ('season', models.CharField(max_length=200, verbose_name='Estação')),
                ('city', models.CharField(max_length=200, verbose_name='Cidade')),
                ('sports', models.ManyToManyField(to='athlete.Sport')),
            ],
        ),
    ]
